include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - bin/**
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    lines_longer_than_80_chars: false
    avoid_catches_without_on_clauses: false
    cascade_invocations: false
    sort_constructors_first: false
    require_trailing_commas: false
    always_use_package_imports: false
    directives_ordering: false
    omit_local_variable_types: false
    unnecessary_parenthesis: false
    avoid_types_on_closure_parameters: false
    prefer_int_literals: false
    unnecessary_null_checks: false
    avoid_equals_and_hash_code_on_mutable_classes: false
