# This file configures the static analysis results for your project (errors,
# warnings, and lints).
#
# This enables the 'recommended' set of lints from `package:lints`.
# This set helps identify many issues that may lead to problems when running
# or consuming Dart code, and enforces writing Dart using a single, idiomatic
# style and format.
#
# If you want a smaller set of lints you can change this to specify
# 'package:lints/core.yaml'. These are just the most critical lints
# (the recommended set includes the core lints).
# The core lints are also what is used by pub.dev for scoring packages.

include: package:very_good_analysis/analysis_options.yaml

# Uncomment the following section to specify additional rules.

linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    avoid_catches_without_on_clauses: false
    cascade_invocations: false
    sort_constructors_first: false
    avoid_dynamic_calls: false
    discarded_futures: false
    avoid_print: false
    prefer_foreach: false
    sort_pub_dependencies: false

analyzer:
  exclude:
    - bin/**
  language:
    strict-raw-types: false
    strict-inference: false

